import React from 'react';

const Privacy = () => {
        return (
          <div className="container">
            <div className="row">
              <div className="col-xs-12 col-md-10 col-md-offset-1">
              <h1><strong>Privacy Policy</strong></h1>
              <p>Last Modified: May 30, 2018</p>
              <p>Winspire, Inc. (&ldquo;Winspire&rdquo; or &ldquo;we&rdquo; or &ldquo;us&rdquo; or &ldquo;our&rdquo;) recognizes the need to protect the privacy of the personal information you provide to Winspire with respect to your access and use of our website (winspire.co) and related services (the &ldquo;Platform&rdquo;).</p>
              <p>Therefore, we have adopted this privacy policy (the &ldquo;Privacy Policy&rdquo;), which sets forth, among other things, the type of information that will be collected, the purpose and use of the collected information, and your rights with regard to the collected information. This Privacy Policy governs how we collect and use your personal information wherever you use our Platform. By accessing the Platform, you are consenting to the collection and the use of your information by us, but only to the extent described herein. Should you wish to revoke your consent, you may do so by contacting us, information on which is set out in the Privacy Policy below.</p>
              <p>Winspire may make modifications, deletions and/or additions to this Privacy Policy (&ldquo;Changes&rdquo;) at any time. Changes will be effective: (i) thirty (30) days after Winspire provides notice of the Changes, whether such notice is provided through the Platform user interface, is sent to the email address associated with your account or otherwise; or (ii) when you opt-in or otherwise expressly agree to the Changes or a version of this Privacy Policy incorporating the Changes, whichever comes first.</p>
              <p><strong>Protection of Your Information</strong></p>
              <p>We are accountable for the information in our custody. Therefore, when we collect or use your information, we will utilize commercially reasonable safeguards to ensure its protection. It should be noted that no security procedure is currently 100% effective. Should any breach of your Personal Information occur, we will inform you as soon as reasonably possible, as required by applicable law.</p>
              <p><strong>Type and Purpose of Collection</strong></p>
              <p>We collect information at various points in the Platform to facilitate its use by our users. Specifically, two types of information are collected:</p>
              <ol>
              <li>Non-Personal Information: Upon accessing the Platform, certain non-personal information will be automatically collected without your knowledge or consent, such as your IP address, location data (which is anonymous and where you log in through the Platform you will be asked if you consent to the Platform accessing your location, which can be updated at any time in your device settings) and the referring website (&ldquo;Non-Personal Information&rdquo;). We use Non-Personal Information to examine our traffic and to view how our customers use the Platform. This type of information will not allow you to be personally identified although we might be able to associate it with your account. For example, we use &ldquo;cookies,&rdquo; which contain only certain statistical information. For more information on cookies please find more information below.</li>
              </ol>
              <ol>
              <li>Identifying Personal Information: To utilize some portions of the Platform, you must first provide personal information that will allow you to be identified, such as your name and e-mail address (&ldquo;Personal Information&rdquo;). This type of information will not be collected without your consent. We expressly acknowledge that we will not use your Personal Information for any other purposes without your consent. The Personal Information we collect will vary depending on how you are using the Platform, but may include, without limitation: (i) your name, mailing address, phone number and email address; (ii) credit card information and charge history; (iii) unique identifiers such as user name, account number and password; (iv) preferences information such as product or content interests, communication or marketing preferences; (v) device information and data; and (vi) Google, Twitter and Facebook identity.</li>
              </ol>
              <p>Additionally, Personal Information may be used and disclosed to the extent Winspire may deem reasonably necessary to enforce the terms of any agreement between you and Winspire, or to protect the rights, property or safety of any person or entity.</p>
              <p><strong>Right to Examine Information</strong></p>
              <p>You have the right to examine any of your Personal Information that we collect. Should you wish to examine such information, please send us a written request to <a className="text underline" href="mailto:legal@winspire.co">legal@winspire.co</a>. We reserve the right to charge you a reasonable administrative fee to access your information, as permitted by applicable law. In certain cases, we may not be able to provide you with access to all of your Personal Information (example: if the information also pertains to the Personal Information of another user).</p>
              <p><strong>Withdrawal of Consent</strong></p>
              <p>You may withdraw your consent to the collection of Personal Information at any time by sending an email to us. Upon receiving notice that you have revoked your consent, we will stop using your Personal Information within a reasonable time, which will vary depending on what information we have collected and for what purpose. Please note that we will send you an email confirmation upon receipt of your request. Therefore, if you do not receive a confirmation email, please contact us again with your request. If you do choose to withdraw such consent, your access to the Platform may be diminished, or your ability to choose some of the options on the Platform may be limited.</p>
              <p>Contact email: <a className="text underline" href="mailto:legal@winspire.co">legal@winspire.co</a></p>
              <p><strong>Sharing Information</strong></p>
              <p>We will not sell, rent or disclose to outside parties the information we collect and save except that we may share the collected information with other parties as follows:</p>
              <ol>
              <li>Affiliated Service Providers: We have agreements with various affiliated service providers to facilitate the functioning of the Platform, with whom we may share the information we have collected. For example, we may share your credit card information with the credit card service provider to process your purchase. Additionally, for example, we may use analytic services.</li>
              <li>Where required by law: We may share the collected information where required by law, specifically in response to a demand from government authorities where such demand meets the legal requirements.</li>
              <li>Statistical Analysis: We may share Non-Personal Information and aggregated information with third parties, including but not limited to for advertising or marketing purposes. No Personal Information will be shared in this manner.</li>
              <li>Transactions: In connection with, or during negotiations of, any merger, sale of company assets, financing or acquisition, or in any other situation where Personal Information may be disclosed or transferred as one of our business assets.<br /></li>
              </ol>
              <p><strong>External Links</strong></p>
              <p>The Platform contains links and references to other websites. We are not responsible for the collection, use and disclosure of information, or the privacy practices of such websites, and we expressly disclaim any liability relating thereto.</p>
              <p><strong>International Visitors</strong><br /></p>
              <p>The Platform is hosted in the United States and is intended for visitors located within the United States. If you choose to use the Service from the European Union or other regions of the world with laws governing data collection and use that may differ from U.S. law, then please note that you are transferring your personal information outside of those regions to the United States for storage and processing. Also, we may transfer your data from the U.S. to other countries or regions in connection with storage and processing of data, fulfilling your requests, and operating the Platform. By providing any information, including personal information, on or to the Service, you consent to such transfer, storage, and processing.&nbsp;</p>
              <p><strong>International Transfer</strong></p>
              <p>Both Personal Information and Non-Personal Information you submit via the Platform is sent to Winspire and will be processed in the USA and stored on secure servers located in the USA. Such information may also be transferred by us to our offices and third parties. The countries concerned may not have similar data protection laws to your country. Where we transfer your information out of your jurisdiction we will take reasonable steps to ensure that your privacy rights continue to be protected. By submitting your information to the Platform, you agree to this storing, processing and transfer.</p>
              <p><strong>Payment Processing</strong></p>
              <p>Payment details you provide will be encrypted using secure sockets layer (SSL) technology before they are submitted over the internet. Payments made on the Platform are made through our payment gateway provider. You will be providing credit or debit card information directly to our payment gateway provider which operates a secure server to process payment details, encrypting your credit/debit card information and authorizing payment. Information which you supply to our payment gateway provider is not within our control and is subject to their own privacy policy and terms and conditions.</p>
              <p><strong>Terms of Service</strong></p>
              <p>This Privacy Policy is incorporated into and forms part of the Terms of Service, which outlines the terms and conditions you agree to when accessing and using the Platform, and which can be found here: <a href="/terms" className="text underline" target="_blank">Terms and conditions</a></p>
              <p><strong>Children&rsquo;s Privacy</strong></p>
              <p>Protecting the privacy of young children is especially important. Our Platform is not directed to children under the age of 13, and we do not knowingly collect personal information from children under the age of 13 without obtaining parental consent. If you are under 13 years of age, then please do not use or access the Platform at any time or in any manner. If we learn that personally identifiable information has been collected on the Platform from persons under 13 years of age and without verifiable parental consent, then we will take the appropriate steps to delete this information. If you are a parent or guardian and discover that your child under 13 years of age has obtained an account on the Platform, then you may alert us at <a className="text underline" href="mailto:legal@winspire.co">legal@winspire.co</a> and request that we delete that child&rsquo;s personally identifiable information from our systems.</p>
              <p><strong>Cookies and Similar Technologies</strong></p>
              <p>When you interact with the Platform, we try to make that experience simple and meaningful. When you use our Platform, our web server sends a cookie to your computer or mobile device (as the case may be). Cookies are small pieces of information which are issued to your computer or mobile device (as the case may be) when you visit a website or access or use a mobile application and which store and sometimes track information about your use of a website or application (as the case may be). A number of cookies we use last only for the duration of your web session or Platform session and expire when you close your browser or exit the Platform. Other cookies are used to remember you when you return to the Platform and will last for longer.</p>
              <p>Some of the cookies used by the Platform are set by us, and some are set by third parties who are delivering services on our behalf.</p>
              <p>Most web and mobile device browsers automatically accept cookies but, if you prefer, you can change your browser to prevent that or to notify you each time a cookie is set. You can also learn more about cookies by visiting www.allaboutcookies.org which includes additional useful information on cookies and how to block cookies using different types of browser or mobile device. Please note, however, that by blocking or deleting cookies used on the Platform, you may not be able to take full advantage of the Platform.</p>
              <p><strong>Additional Individual Rights </strong></p>
              <p>If you are a resident of the EEA or Switzerland, you are entitled to the following rights:</p>
              <ul>
              <li>The right to request data erasure &ndash; you have the right to have your data erased from the Platform if the data is no longer necessary for the purpose for which it was collected, you withdraw consent and no other legal basis for processing exists, or you believe your fundamental rights to data privacy and protection outweigh our legitimate interest in continuing the processing. </li>
              </ul>
              <ul>
              <li>The right to restrict or object to our processing &ndash; you have the right to restrict or object to our processing if we are processing your data based on legitimate interests or the performance of a task in the public interest as an exercise of official authority (including profiling); using your data for direct marketing (including profiling); or processing your data for purposes of scientific or historical research and statistics.</li>
              </ul>
              <ul>
              <li>The right to object to automated decision making &ndash; you have a right to avoid being subject to automated decision making and insist on human intervention if we make an automated decision that produces a legal or a similarly significant effect on you.</li>
              </ul>
              <p><strong>Accessing and Updating Personal Information</strong></p>
              <p>Upon request we will provide you with information about whether we hold, or process on behalf of a third party, any of your personal information. When you use the Platform we make good faith efforts to provide you with access to your personal information and either to correct this data if it is inaccurate or to delete such data at your request if it is not for legitimate business purposes. You may update your account information by logging into your account. When requests come to Winspire with regard to personal information, we ask individual users to identify themselves and the information requested to be accessed, corrected or removed before processing such requests, and we may decline to process requests that are unreasonably repetitive or systematic, require disproportionate technical effort, jeopardize the privacy of others, or would be extremely impractical (for instance, requests concerning information residing on backup tapes), or for which access is not otherwise required. We retain and use your information as necessary to comply with our legal obligations, resolve disputes and enforce our agreements. In any case where we provide information access and correction, we perform this service free of charge, except if doing so would require a disproportionate effort. We will respond to these requests within a reasonable timeframe.</p>
              <p>We will retain your information for as long as your account is active or as needed to provide you services. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.</p>
              <p><strong>Recourse, Enforcement and Liability </strong></p>
              <p>In compliance with the EU-U.S Privacy Shield, Winspire commits to resolve complaints about privacy and personal data collection or use. EU individuals with inquiries or complaints regarding this Policy should first contact Winspire at the address given below. Winspire will investigate and attempt to resolve such complaints by reference to the principles contained in this Policy.</p>
              <p>Winspire is subject to the investigative and enforcement authority of the Federal Trade Commission (FTC) and is obliged to disclose personal data in response to lawful requests by public authorities, for law enforcement and national security purposes, and has potential liability for onward transfers to third parties. </p>
              <p>Winspire will conduct compliance audits of its relevant privacy practices to verify adherence to this Policy. Any employee that Winspire determines is in violation of this policy may be subject to disciplinary action.</p>
              <p><strong>Our Contact Information</strong></p>
              <p>Please contact us with any questions or comments about this Policy, your personal information, our use and disclosure practices, or your consent choices by email at <a className="text underline" href="mailto:legal@winspire.co">legal@winspire.co</a></p>
              <p>Winspire, Inc. </p>
              <p>2651 S Palm Aire Dr #301</p>
              <p>Pompano Beach, FL 33069</p>
              </div>
            </div>
          </div>
        );
}
export default Privacy ;
