import React from 'react';

const Terms = () => {
        return (
            <div className="container">
              <div className="row">
                <div className="col-xs-12 col-md-10 col-md-offset-1">
                  <h1><strong>Terms of Service</strong></h1>
                  <p>Last Modified: May 11, 2018</p>
                  <p><strong>1. User&rsquo;s Acknowledgment and Acceptance of Terms</strong></p>
                  <p>Winspire, Inc. (&ldquo;Us,&rdquo; &ldquo;We,&rdquo; &ldquo;Winspire,&rdquo; or the &ldquo;Company&rdquo;) provides the winspire.co website and various related services (collectively, the &ldquo;Platform&rdquo;) to you, the user, subject to your compliance with all the terms, conditions, and notices contained or referenced herein (the &ldquo;Terms of Service&rdquo; or &ldquo;Agreement&rdquo;), as well as any other written agreement between us and you. All such guidelines or rules are hereby incorporated by reference into these Terms of Service.</p>
                  <p>You are permitted to use the Platform, only if you: (1) Represent that you are able to form a binding contract in your jurisdiction; (2) Comply with our Terms of Service; (3) Will not copy or distribute any part of any part of the Platform in any medium without Company&rsquo;s prior written authorization except as permitted through the Platform&rsquo;s functionality and under these Terms of Service; (4) Provide accurate and complete information when creating an account; (5) Acknowledge you are solely responsible for the activity that occurs while signed in to or while using the Platform; (6) Don&rsquo;t collect any personally identifiable information, including full names, physical addresses, or e-mail addresses, for commercial purposes; and (7) Acknowledge your sole responsibility for your content submissions, including discussion posts, profile information and links, pictures, and other such content. The Platform is available only to, and may only be used by individuals who can form legally binding contracts under applicable law. Without limiting the foregoing, the Platform is not available to children (persons under the age of 18) or users who have had their user account temporarily or permanently deactivated. By becoming a user, you represent and warrant that you are at least 18 years old and that you have the right, authority, and capacity to enter into and abide by the terms and conditions of this Agreement.</p>
                  <p>YOUR USE OF THE PLATFORM CONSTITUTES YOUR AGREEMENT TO BE BOUND BY THESE TERMS OF SERVICE. IF YOU DO NOT WISH TO BE BOUND BY THE THESE TERMS OF SERVICE, PLEASE EXIT THE PLATFORM NOW. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THE PLATFORM, OR ANY PRODUCTS, SERVICES, CONTENT, OR OTHER INFORMATION AVAILABLE ON OR THROUGH THE PLATFORM, IS TO STOP USING THE PLATFORM AND/OR THOSE PARTICULAR PRODUCTS OR SERVICES. YOUR AGREEMENT WITH US REGARDING COMPLIANCE WITH THESE TERMS OF SERVICE BECOMES EFFECTIVE IMMEDIATELY UPON COMMENCEMENT OF YOUR USE OF THE PLATFORM.</p>
                  <p>In these Terms of Service, we use the terms &ldquo;you&rdquo; and &ldquo;your&rdquo; to mean any person using our Platform, and any organization or person using the Platform on an organization&rsquo;s behalf. </p>
                  <p><strong>2. Overview of our Services</strong></p>
                  <p>Winspire is social learning platform to help professionals build their soft skills focused on Career growth, Personal growth and Leadership. Our mission is to create learning communities that help ordinary people do Extraordinary things in life and be an inspiration for their families and communities. </p>
                  <p><strong>3. Account Information and Security</strong></p>
                  <p>When you register, you provide us with some basic information, such as a phone number or email address. Keep your email address and other account information current and accurate. You alone are responsible for anything that happens from your failure to maintain security and confidentiality, such as by sharing your account credentials with others. If someone is using your account, notify us immediately.</p>
                  <p><strong>4. Feedback</strong></p>
                  <p>We always appreciate feedback and are always on the lookout for ways to improve Company. For feedback, comments, questions, or concerns, you can contact us at <a className="text underline" href="mailto:legal@winspire.co">legal@winspire.co</a> and we will return you e-mail at the soonest opportunity possible. </p>
                  <p><strong>5. Payments</strong></p>
                  <p>Your right to use certain services on the Platform may be conditional upon our receipt of payment of all fees owed to Winspire. If payment cannot be charged to your credit card or if a charge is refunded for any reason, we reserve the right to immediately either suspend or terminate your access and account, thereby terminating this Agreement and all our obligations hereunder. We reserve the right to change any of the fees that we charge, or to institute new or additional fees, at any time upon notice to you.</p>
                  <p><strong>6. Guarantee and Warranty</strong></p>
                  <p>Use of the Platform is at your sole risk. All materials, information, products, software, programs, and services are provided &ldquo;as is,&rdquo; with no warranties or guarantees whatsoever. Winspire expressly disclaims to the fullest extent permitted by law all express, implied, statutory, and other warranties, guarantees, or representations, including, without limitation, the warranties of merchantability, fitness for a particular purpose, and non-infringement of proprietary and intellectual property rights. Without limitation, Winspire makes no warranty or guarantee that the Platform will be uninterrupted, timely, secure, or error-free. You understand and agree that if you download or otherwise obtain materials, information, products, software, programs, or services, you do so at your own discretion and risk and that you will be solely responsible for any damages that may result, including loss of data or damage to your computer system. Some jurisdictions do not allow the exclusion of warranties, so the above exclusions may not apply to you.</p>
                  <p><strong>7. Release</strong></p>
                  <p>In the event that you have a dispute with a user of the Platform you agree to release Winspire (including our affiliates and each of our respective officers, directors, employees, agents, shareholders, and suppliers) from claims, demands and damages of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected to such disputes with other users. Additionally, you expressly waive any rights you may have under California Civil Code Section 1542 (or analogous laws of other states), which says: &ldquo;A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.&rdquo; We reserve the right, but have no obligation, to monitor disputes between you and other users.<br /></p>
                  <p><strong>8. Limitation of Liability</strong></p>
                  <p>IN NO EVENT WILL WINSPIRE BE LIABLE TO ANY PARTY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY TYPE WHATSOEVER RELATED TO OR ARISING FROM THE PLATFORM OR ANY USE OF THE PLATFORM, OR OF ANY SITE OR RESOURCE LINKED TO, REFERENCED, OR ACCESSED THROUGH THE PLATFORM, OR FOR THE USE OR DOWNLOADING OF, OR ACCESS TO, ANY MATERIALS, INFORMATION, PRODUCTS, OR SERVICES, INCLUDING, WITHOUT LIMITATION, ANY LOST PROFITS, BUSINESS INTERRUPTION, LOST SAVINGS OR LOSS OF PROGRAMS OR OTHER DATA, EVEN IF WINSPIRE IS EXPRESSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THIS EXCLUSION AND WAIVER OF LIABILITY APPLIES TO ALL CAUSES OF ACTION, WHETHER BASED ON CONTRACT, WARRANTY, TORT, OR ANY OTHER LEGAL THEORIES.</p>
                  <p><strong>9. Dispute Resolution and Arbitration</strong></p>
                  <p>In the interest of resolving disputes between you and Winspire in the most expedient and cost effective manner, you and Winspire agree that every dispute arising in connection with these Terms of Service will be resolved by binding arbitration. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and is subject to very limited (if any) review by courts. Arbitrators can award the same damages and relief that a court can award. This agreement to arbitrate disputes includes all claims arising out of or relating to any aspect of these Terms of Service, whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of these Terms. YOU UNDERSTAND AND AGREE THAT, BY ENTERING INTO THESE TERMS OF SERVICE, YOU AND WINSPIRE ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS, COLLECTIVE, OR REPRESENTATIVE ACTION.&nbsp;</p>
                  <p>Despite the provisions of the preceding paragraph, nothing in these Terms of Service will be deemed to waive, preclude, or otherwise limit the right of either party to: (a) bring an individual action in small claims court; (b) pursue an enforcement action through the applicable federal, state, or local agency if that action is available; (c) seek injunctive relief in a court of law; or (d) to file suit in a court of law to address an intellectual property infringement claim.&nbsp;</p>
                  <p>Arbitrator</p>
                  <p>Any arbitration between you and Winspire will be settled under the Federal Arbitration Act, and governed by the Commercial Dispute Resolution Procedures and the Supplementary Procedures for Consumer Related Disputes (collectively, &ldquo;AAA Rules&rdquo;) of the American Arbitration Association (&ldquo;AAA&rdquo;), as modified by these Terms, and will be administered by the AAA. The AAA Rules and filing forms are available online at <a className="text underline" href="http://www.adr.org">www.adr.org</a>, by calling the AAA at 1-800-778-7879, or by contacting Winspire at [<a className="text underline" href="mailto:legal@winspire.co">legal@winspire.co</a>].</p>
                  <p>Notice; Process</p>
                  <p>A party who intends to seek arbitration must first send a written notice of the dispute to the other party by certified U.S. Mail or by Federal Express (signature required) or, only if such other party has not provided a current physical address, then by electronic mail (&ldquo;Notice&rdquo;). Winspire&rsquo;s address for Notice is: Winspire, Inc. [2651 S Palm Aire Dr, #301, Pompano Beach, FL 33069. The Notice must: (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought (&ldquo;Demand&rdquo;). The parties will make good faith efforts to resolve the claim directly, but if the parties do not reach an agreement to do so within 30 days after the Notice is received, you or Winspire may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by you or Winspire must not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any. If the dispute is finally resolved through arbitration in your favor, Winspire will pay you the highest of the following: (i) the amount awarded by the arbitrator, if any; (ii) the last written settlement amount offered by Winspire in settlement of the dispute prior to the arbitrator&rsquo;s award; or (iii) $1,000. &nbsp;</p>
                  <p>Fees and Procedure</p>
                  <p>The parties to the arbitration shall each pay an equal share of the costs and expenses of such arbitration, and each party shall separately pay for its respective counsel fees and expenses; provided, however, that the arbitrator may award attorneys&rsquo; fees and costs to the prevailing party, except as prohibited by law. If you commence arbitration in accordance with these Terms of Services, Winspire will reimburse you for your payment of the filing fee, unless your claim is for more than $10,000, in which case the payment of any fees will be decided by the AAA Rules. Any arbitration hearing will take place at a location to be agreed upon in Broward County, Florida, but if the claim is for $10,000 or less, you may choose whether the arbitration will be conducted: (a) solely on the basis of documents submitted to the arbitrator; (b) through a non-appearance based telephone hearing; or (c) by an in-person hearing as established by the AAA Rules in the county (or parish) of your billing address. If the arbitrator finds that either the substance of your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all fees will be governed by the AAA Rules. In that case, you agree to reimburse Winspire for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator must issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based. The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees or expenses at any time during the proceeding and upon request from either party made within 14 days of the arbitrator&rsquo;s ruling on the merits. &nbsp;</p>
                  <p>The arbitrator may grant injunctions and other relief. The arbitrator shall administer and conduct any arbitration in accordance with the law of the jurisdiction in which the dispute arose, including civil procedure rules, and the arbitrator shall apply the substantive and procedural law of the jurisdiction in which the dispute arose. To the extent that the AAA Rules conflict with local law, local law shall take preference. The decision of the arbitrator shall be final, conclusive, and binding on the parties to the arbitration. The parties agree that the prevailing party in any arbitration shall be entitled to injunctive relief in any court of competent jurisdiction to enforce the arbitration award.</p>
                  <p>No Class Actions</p>
                  <p>YOU AND WINSPIRE AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR MEMBER OF ANY CLASS, COLLECTIVE, OR REPRESENTATIVE PROCEEDING except that users may bring a proceeding as a private attorney general, if and as allowed by law. Further, unless both you and Winspire agree otherwise, the arbitrator may not consolidate more than one person&rsquo;s claims, and may not otherwise preside over any form of a representative or class proceeding. Nothing in this Agreement infringes upon any rights a user may have under the Sarbanes-Oxley Act, including any rights prohibiting compulsory arbitration.</p>
                  <p>Modifications to this Arbitration Provision</p>
                  <p>If Winspire makes any future change to this arbitration provision, other than a change to Winspire&rsquo;s address for Notice, you may reject the change by sending us written notice within 30 days of the change to Winspire&rsquo;s address for Notice, in which case your account with Winspire will be immediately terminated and this arbitration provision, as in effect immediately prior to the changes you rejected will survive.</p>
                  <p>Enforceability</p>
                  <p>If the &ldquo;No Class Actions&rdquo; section is found to be unenforceable or if the entirety of this Section 9 is found to be unenforceable, then the entirety of this Section 9 will be null and void and, in that case, the parties agree that the exclusive jurisdiction and venue described in Section 10 will govern any action arising out of or related to these Terms of Service.</p>
                  <p>Right to Opt Out of Arbitration</p>
                  <p>You may submit a statement notifying Winspire that you wish to opt out and not be subject to arbitration under this section. Should you desire to opt out, you must notify Winspire of your intention to opt out by submitting a written notice, which may be via email to <a className="text underline" href="mailto:legal@winspire.co">legal@winspire.co</a> stating that you are opting out of this section. In order to be effective, your opt out notice must be provided within thirty (30) days of your agreeing to these Terms. Should you timely opt out of this section, you may pursue available legal remedies and will not be required to arbitrate claims.</p>
                  <p><strong>10. Choice of Law; Venue</strong></p>
                  <p>These Terms are governed by and construed in accordance with the laws of the State of Florida, United States of America, without giving effect to any conflict of law principles, except as may be otherwise provided in supplemental terms applicable to your region. The venue for any disputes arising from or concerning this Agreement or use of the Platform shall be in Broward County, Florida.</p>
                  <p><strong>11. Termination of Service</strong></p>
                  <p>Winspire may terminate your privilege to use or access the Platform immediately and without notice for any reason whatsoever.&nbsp;Upon such termination, you must immediately cease accessing or using the Platform and agree not access or make use of, or attempt to use, the Platform. Furthermore, you acknowledge that Winspire reserves the right to take action -- technical, legal or otherwise -- to block, nullify or deny your ability to access the Platform. You understand that Winspire may exercise this right in its sole discretion, and this right shall be in addition to and not in substitution for any other rights and remedies available to Winspire.</p>
                  <p>All provisions of these Terms of Service which by their nature should survive termination shall survive the termination of your access to the Platform, including, without limitation, provision regarding ownership, warranty disclaimers, indemnity, and limitations of liability.</p>
                  <p><strong>12. Intellectual Property</strong></p>
                  <p>The entire content and materials contained on the Platform, including, but not limited to, audio, video, images, text, user interface, scores, logos, the selection and arrangement of the Platform and other intellectual property (the &ldquo;Content&rdquo;) are owned by or licensed to Winspire to the fullest extent under the copyright laws of the United States and other countries. Images of people or places displayed on the Platform are either the property of, or used with permission by, Winspire. You may not reproduce, republish, transmit, upload, distribute, copy or publicly display any of the Content without our prior written consent. We neither warrant nor represent that your use of materials displayed on the Platform will not infringe rights of third parties not owned by or affiliated with the Company. We may redesign the Platform in our sole discretion at any time.</p>
                  <p><strong>13. Content</strong></p>
                  <p>When you upload content on the Platform as a course creator or provide it to Winspire (&ldquo;Learning Content&rdquo;), you represent and warrant that you have the right, power, and authority to post that Learning Content and grant the licenses specified below. You further represent and warrant that by posting or providing such Learning Content you will not violate third-party rights of any kind, including, without limitation, any Intellectual Property Rights, rights of publicity, and privacy rights. To the extent your Learning Content may be copyrightable, you represent, warrant, and covenant that you are the owner of all the copyright rights to such Learning Content and that Winspire may exercise the rights to your Learning Content granted under the Terms of Service&nbsp;without any liability or obligation for any payment.</p>
                  <p>You retain all ownership rights in any Learning Content you post on the Platform.&nbsp;To the extent permitted by applicable law, you also grant to Winspire and our successors and Affiliates a royalty-free, sub-licensable, transferable, perpetual, irrevocable, non-exclusive, worldwide license to use, reproduce, modify, publish, list information regarding, edit, translate, distribute, publicly perform, publicly display, and make derivative works of all such Learning Content and your name, voice, and/or likeness as contained in your Learning Content, in whole or in part, and in any form, media, or technology, whether now known or hereafter developed, for use in connection with the Platform and Winspire&rsquo;s (and our successors&rsquo; and Affiliates&rsquo;) business, including, without limitation, for promoting and redistributing part or all of the Platform (and derivative works thereof) in any media formats and through any media channels.&nbsp;You also hereby grant each User a non-exclusive license to access your Learning Content through the Platform and to use, reproduce, distribute, display, and perform such Learning Content to the extent permitted through the normal functionality of the Platform and subject to all applicable confidentiality and other provisions of this Agreement, our Privacy Policy, and applicable law.</p>
                  <p>Notwithstanding the foregoing paragraph, Winspire will only use or disclose Learning Content you post to any non-public area of the Platform to the extent necessary to provide services to you.</p>
                  <p>The licenses to Learning Content granted by you in this Agreement will terminate within a commercially reasonable time after you remove or delete your Learning Content from the Platform, except that you grant Winspire and our successors and Affiliates the irrevocable and perpetual license to retain and use, but not publicly display or distribute, server or archival copies of all Learning Content that you have removed or deleted to the extent permitted by applicable law.</p>
                  <p><strong>14. Restrictions on Use</strong></p>
                  <p>You may not use the Platform or contents set forth therein for any illegal purpose or in any manner inconsistent with the Terms of Service. You agree to use the service solely for your own use and benefit, and not for resale or other transfer or disposition to, or use by or for the benefit of, any other person or entity. You agree not to use, transfer, distribute, or dispose of any information contained in the service in any manner that could compete with the business of Company. You may not copy, reproduce, recompile, disassemble, decompile, reverse engineer, distribute, modify, publish, display, perform, upload to, create derivative works from, frame transmit, or in any way exploit any part of the service, you may not recirculate, redistribute or publish the analysis and presentation included in the service without Company&rsquo;s prior written consent.</p>
                  <p>Modification of Company&rsquo;s content is a violation of the copyrights and other proprietary rights of Company or its subsidiaries. Additionally, you may not monetize or offer any part of the service for sale or distribute it over any other medium including but not limited to a computer network or hyperlink framing on the internet without the prior written consent of Company. The Platform and the information contained therein may not be used to construct a database of any kind. The Platform and content contained therein may not be stored (in its entirety or in any part) in databases for access by you or any third party or to distribute.</p>
                  <p>In the absence of a contrary agreement, you may not use any of the trademarks, trade names, service marks, copyrights, or logos of Company or its subsidiaries suppliers or affiliates in any manner which creates the impression that such items belong to or are associated with you or, except as otherwise provided herein, are used with Company&rsquo;s consent, and you acknowledge that you have no ownership rights in and to any of such items. You will not use the service or the information contained therein in unsolicited mailings or spam material. You will not use any trademarks, trade names, service marks, copyrights, or logos of Company or its subsidiaries in unsolicited mailings or spam material. You will not spam or send unsolicited mailings to any person or entity using the service.</p>
                  <p><strong>15. No Agency</strong></p>
                  <p>No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship between you and Winspire is intended or created by this Agreement. </p>
                  <p><strong>16. Digital Millennium Copyright Act</strong></p>
                  <p>We comply with the provisions of the Digital Millennium Copyright Act applicable to internet service providers (17 U.S.C. &sect;512, as amended). If you have an intellectual property rights-related complaint about material posted on the Platform, you may contact our Designated Agent at the following address:</p>
                  <p>Winspire, Inc.</p>
                  <p>2651 S Palm Aire Dr #301, </p>
                  <p>Pompano Beach, FL 33069</p>
                  <p>Any notice alleging that materials hosted by or distributed through the Platform infringe intellectual property rights must include the following information:&nbsp;</p>
                  <ol>
                  <li>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other right being infringed;&nbsp;</li>
                  <li>A description of the copyright-protected work or other intellectual property right that you claim has been infringed;&nbsp;</li>
                  <li>A description of the material that you claim is infringing and where it is located on the Service;&nbsp;</li>
                  <li>Your address, telephone number, and email address;&nbsp;</li>
                  <li>A statement by you that you have a good faith belief that the use of those materials on the Service is not authorized by the copyright owner, its agent, or the law; and&nbsp;</li>
                  <li>A statement by you that the above information in your notice is accurate and that, under penalty of perjury, you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner&#39;s behalf.</li>
                  </ol>
                  <p>Winspire will promptly terminate without notice the accounts of users that are determined by Winspire to be &ldquo;Repeat Infringers.&rdquo; A Repeat Infringer is a user who has been notified of infringing activity or has had Learning Content removed from the Platform at least twice.</p>
                  <p><strong>17. Links to Other Sites and Materials</strong></p>
                  <p>As part of using the Platform, Winspire may provide you with links to third party website(s) (&ldquo;Third Party Sites&rdquo;) as well as content or items belonging to or originating from third parties (the &ldquo;Third Party Applications, Software or Content&rdquo;). Winspire has no control over Third Party Sites and Third Party Applications, Software, or Content or the promotions, materials, information, goods or services available on these Third Party Sites or Third Party Applications, Software, or Content.&nbsp;Such Third Party Sites and Third Party Applications, Software, or Content are not investigated, monitored or checked for accuracy, appropriateness, or completeness by Winspire, and Winspire is not responsible for any Third Party Sites accessed through the Platform or any Third Party Applications, Software, or Content posted on, available through or installed from the Platform, including the content, accuracy, offensiveness, opinions, reliability, privacy practices or other policies of or contained in the Third Party Sites or the Third Party Applications, Software or Content. Inclusion of, linking to, or permitting the use or installation of any Third Party Site or any Third Party Applications, Software, or Content does not imply approval or endorsement thereof by Winspire. If you decide to leave the Platform and access the Third Party Sites or to use or install any Third Party Applications, Software or, Content, you do so at your own risk and you should be aware that our terms and policies no longer govern. You should review the applicable terms and policies, including privacy and data gathering practices, of any site to which you navigate from the Platform or relating to any applications you use or install from the site.</p>
                  <p><strong>18. Privacy</strong></p>
                  <p>Winspire&rsquo;s current privacy policy is available on the Platform and at our website (<a href="/privacy" className="text underline" target="_blank">Privacy Policy</a>) (the &ldquo;Privacy Policy&rdquo;), which is incorporated by this reference. In accordance with the Privacy Policy, we may collect information about the location of your device each time you use the Platform, or when you otherwise consent to the collection of this information.</p>
                  <p> We strongly recommend that you review the Privacy Policy closely.</p>
                  <p><strong>19. Electronic Communications</strong></p>
                  <p>The communications between you and Company use electronic means, whether you use the Platform or send us emails, or whether Company posts notices on the service or communicates with you via email. For contractual purposes, you (a) consent to receive communications from Company in an electronic form; and (b) agree that all terms and conditions, agreements, notices, disclosures, and other communications that Company provides to you electronically satisfy any legal requirement that such communications would satisfy if it were in writing. </p>
                  <p><strong>20. Notice</strong></p>
                  <p>Communications made through the Service&rsquo;s e-mail and messaging system, will not constitute legal notice to Company or any of its officers, employees, agents or representatives in any situation where notice to Company is required by contract or any law or regulation.</p>
                  <p>Any such notice must be sent to:</p>
                  <p>Winspire, Inc.<br />2651 S Palm Aire Dr, #301</p>
                  <p>Pompano Beach, FL 33069</p>
                  <p>Under California Civil Code Section 1789.3, California users of the Platform receive the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1020 N Street, #501, Sacramento, California 95814, or by telephone at 1-916-445-1254.<br /></p>
                  <p><strong>21. Changes and Amendments to Terms</strong></p>
                  <p>These Terms of Service are effective as of the &ldquo;Last Modified&rdquo; date identified at the top of this page. We expressly reserve the right to change these Terms of Service from time to time without notice to you. You acknowledge and agree that it is your responsibility to review the Platform and these Terms of Service from time to time and to familiarize yourself with any modifications. Your continued use of the Platform after such modifications will constitute acknowledgement of the modified Terms of Service and agreement to abide and be bound by the modified Terms of Service. However, for any material modifications to the Terms of Service or in the event that such modifications materially alter your rights or obligations hereunder, such amended Terms of Service will automatically be effective upon the earlier of (i) your continued use of the Platform with actual knowledge of such modifications, or (ii) 30 days from publication of such modified Terms of Service on the Platform. Notwithstanding the foregoing, the resolution of any dispute that arises between you and us will be governed by the Terms of Service in effect at the time such dispute arose.</p>
                  <p><strong>22. General Terms</strong></p>
                  <p>If any part of this Agreement is held invalid or unenforceable, that portion of the Agreement will be construed consistent with applicable law. The remaining portions will remain in full force and effect. Any failure on the part of Company to enforce any provision of this Agreement will not be considered a waiver of our right to enforce such provision. Our rights under this Agreement will survive any termination of this Agreement.</p>
                  <p>Company may assign or delegate these Terms of Service and/or Company&rsquo;s Privacy Policy, in whole or in part, to any person or entity at any time with or without your consent, including, but not limited, to a subsidiary or an acquirer of assets. You may not assign or delegate any rights or obligations under the Terms of Service or Privacy Policy without Company&rsquo;s prior written consent, and any unauthorized assignment and delegation by you is void.</p>
                  <p>YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF USE, UNDERSTAND THE TERMS OF USE, AND WILL BE BOUND BY THESE TERMS AND CONDITIONS. YOU FURTHER ACKNOWLEDGE THAT THESE TERMS OF USE TOGETHER WITH THE PRIVACY POLICY REPRESENT THE COMPLETE AND EXCLUSIVE STATEMENT OF THE AGREEMENT BETWEEN US AND THAT IT SUPERSEDES ANY PROPOSAL OR PRIOR AGREEMENT ORAL OR WRITTEN, AND ANY OTHER COMMUNICATIONS BETWEEN US RELATING TO THE SUBJECT MATTER OF THIS AGREEMENT.</p>

                </div>
              </div>
            </div>
        );
}
export default Terms ;
